### ISSUE TITLE
multi channel augmentation

### ISSUE THREAD

**Issue by ethancohen123** [crosszamirski/Multi-Channel-dino#1]
Hi,
FYI I think there is albumentations that does the job at providing augmentations for any numbers of channels :)
Let me know if this is relevant

**Comment by crosszamirski** [comment]
> Hi, FYI I think there is albumentations that does the job at providing augmentations for any numbers of channels :) Let me know if this is relevant

I think this is what I use? The "additional_targets={" part. Unless there is something else I haven't seen
However this script is a bit clunky as it loads each channel separately and manually - mostly in response to meta data formats etc

**Comment by ethancohen123** [comment]
Oh okay I didnt catch that since you were loading each channel separately (forgot about messy metadata for each channel aha )
